//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace Box.GetPlayerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetPlayerServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GetPlayerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlayerProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMatchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPlayerService() {
            this.Url = global::Box.Properties.Settings.Default.Box_GetPlayerService_GetPlayerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetPlayerProfileCompletedEventHandler GetPlayerProfileCompleted;
        
        /// <remarks/>
        public event getMatchCompletedEventHandler getMatchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlayerProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public player_profile GetPlayerProfile(string server, string playerId) {
            object[] results = this.Invoke("GetPlayerProfile", new object[] {
                        server,
                        playerId});
            return ((player_profile)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlayerProfileAsync(string server, string playerId) {
            this.GetPlayerProfileAsync(server, playerId, null);
        }
        
        /// <remarks/>
        public void GetPlayerProfileAsync(string server, string playerId, object userState) {
            if ((this.GetPlayerProfileOperationCompleted == null)) {
                this.GetPlayerProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlayerProfileOperationCompleted);
            }
            this.InvokeAsync("GetPlayerProfile", new object[] {
                        server,
                        playerId}, this.GetPlayerProfileOperationCompleted, userState);
        }
        
        private void OnGetPlayerProfileOperationCompleted(object arg) {
            if ((this.GetPlayerProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlayerProfileCompleted(this, new GetPlayerProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public match getMatch(string id, string server, string playerId) {
            object[] results = this.Invoke("getMatch", new object[] {
                        id,
                        server,
                        playerId});
            return ((match)(results[0]));
        }
        
        /// <remarks/>
        public void getMatchAsync(string id, string server, string playerId) {
            this.getMatchAsync(id, server, playerId, null);
        }
        
        /// <remarks/>
        public void getMatchAsync(string id, string server, string playerId, object userState) {
            if ((this.getMatchOperationCompleted == null)) {
                this.getMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMatchOperationCompleted);
            }
            this.InvokeAsync("getMatch", new object[] {
                        id,
                        server,
                        playerId}, this.getMatchOperationCompleted, userState);
        }
        
        private void OngetMatchOperationCompleted(object arg) {
            if ((this.getMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMatchCompleted(this, new getMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class player_profile {
        
        private string player_idField;
        
        private string serverField;
        
        private string iconField;
        
        private string levelField;
        
        private string fightingField;
        
        private string first_winField;
        
        private com_champ[] com_champField;
        
        private normal_statistics[] normal_statistics_listField;
        
        private rank_statistics[] rank_statistics_listField;
        
        private played_champs_display[] played_champs_display_listField;
        
        private match_list[] match_list_listField;
        
        /// <remarks/>
        public string player_id {
            get {
                return this.player_idField;
            }
            set {
                this.player_idField = value;
            }
        }
        
        /// <remarks/>
        public string server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string fighting {
            get {
                return this.fightingField;
            }
            set {
                this.fightingField = value;
            }
        }
        
        /// <remarks/>
        public string first_win {
            get {
                return this.first_winField;
            }
            set {
                this.first_winField = value;
            }
        }
        
        /// <remarks/>
        public com_champ[] com_champ {
            get {
                return this.com_champField;
            }
            set {
                this.com_champField = value;
            }
        }
        
        /// <remarks/>
        public normal_statistics[] normal_statistics_list {
            get {
                return this.normal_statistics_listField;
            }
            set {
                this.normal_statistics_listField = value;
            }
        }
        
        /// <remarks/>
        public rank_statistics[] rank_statistics_list {
            get {
                return this.rank_statistics_listField;
            }
            set {
                this.rank_statistics_listField = value;
            }
        }
        
        /// <remarks/>
        public played_champs_display[] played_champs_display_list {
            get {
                return this.played_champs_display_listField;
            }
            set {
                this.played_champs_display_listField = value;
            }
        }
        
        /// <remarks/>
        public match_list[] match_list_list {
            get {
                return this.match_list_listField;
            }
            set {
                this.match_list_listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class com_champ {
        
        private string champion_name_chField;
        
        private string champion_nameField;
        
        private string iconField;
        
        private string countField;
        
        /// <remarks/>
        public string champion_name_ch {
            get {
                return this.champion_name_chField;
            }
            set {
                this.champion_name_chField = value;
            }
        }
        
        /// <remarks/>
        public string champion_name {
            get {
                return this.champion_nameField;
            }
            set {
                this.champion_nameField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class items {
        
        private string playerIdField;
        
        private string matchIdField;
        
        private string itemIcon1Field;
        
        private string itemName1Field;
        
        private string itemDesc1Field;
        
        private string itemIcon2Field;
        
        private string itemName2Field;
        
        private string itemDesc2Field;
        
        private string itemIcon3Field;
        
        private string itemName3Field;
        
        private string itemDesc3Field;
        
        private string itemIcon4Field;
        
        private string itemName4Field;
        
        private string itemDesc4Field;
        
        private string itemIcon5Field;
        
        private string itemName5Field;
        
        private string itemDesc5Field;
        
        private string itemIcon6Field;
        
        private string itemName6Field;
        
        private string itemDesc6Field;
        
        private string itemIcon7Field;
        
        private string itemName7Field;
        
        private string itemDesc7Field;
        
        /// <remarks/>
        public string playerId {
            get {
                return this.playerIdField;
            }
            set {
                this.playerIdField = value;
            }
        }
        
        /// <remarks/>
        public string matchId {
            get {
                return this.matchIdField;
            }
            set {
                this.matchIdField = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon1 {
            get {
                return this.itemIcon1Field;
            }
            set {
                this.itemIcon1Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName1 {
            get {
                return this.itemName1Field;
            }
            set {
                this.itemName1Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc1 {
            get {
                return this.itemDesc1Field;
            }
            set {
                this.itemDesc1Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon2 {
            get {
                return this.itemIcon2Field;
            }
            set {
                this.itemIcon2Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName2 {
            get {
                return this.itemName2Field;
            }
            set {
                this.itemName2Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc2 {
            get {
                return this.itemDesc2Field;
            }
            set {
                this.itemDesc2Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon3 {
            get {
                return this.itemIcon3Field;
            }
            set {
                this.itemIcon3Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName3 {
            get {
                return this.itemName3Field;
            }
            set {
                this.itemName3Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc3 {
            get {
                return this.itemDesc3Field;
            }
            set {
                this.itemDesc3Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon4 {
            get {
                return this.itemIcon4Field;
            }
            set {
                this.itemIcon4Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName4 {
            get {
                return this.itemName4Field;
            }
            set {
                this.itemName4Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc4 {
            get {
                return this.itemDesc4Field;
            }
            set {
                this.itemDesc4Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon5 {
            get {
                return this.itemIcon5Field;
            }
            set {
                this.itemIcon5Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName5 {
            get {
                return this.itemName5Field;
            }
            set {
                this.itemName5Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc5 {
            get {
                return this.itemDesc5Field;
            }
            set {
                this.itemDesc5Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon6 {
            get {
                return this.itemIcon6Field;
            }
            set {
                this.itemIcon6Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName6 {
            get {
                return this.itemName6Field;
            }
            set {
                this.itemName6Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc6 {
            get {
                return this.itemDesc6Field;
            }
            set {
                this.itemDesc6Field = value;
            }
        }
        
        /// <remarks/>
        public string itemIcon7 {
            get {
                return this.itemIcon7Field;
            }
            set {
                this.itemIcon7Field = value;
            }
        }
        
        /// <remarks/>
        public string itemName7 {
            get {
                return this.itemName7Field;
            }
            set {
                this.itemName7Field = value;
            }
        }
        
        /// <remarks/>
        public string itemDesc7 {
            get {
                return this.itemDesc7Field;
            }
            set {
                this.itemDesc7Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class matchDetails {
        
        private string matchIdField;
        
        private string playerIdField;
        
        private string goldField;
        
        private string kDAField;
        
        private string champion_nameField;
        
        private string champion_name_chField;
        
        private string champIconField;
        
        private string firstSpellIconField;
        
        private string secondSpellIconField;
        
        private string warScoreField;
        
        private string lastHitsField;
        
        private string creepsField;
        
        private string towersDestroyedField;
        
        private string barracksDestroyedField;
        
        private string wardsField;
        
        private string dewardsField;
        
        private string maxContKillsField;
        
        private string maxMultiKillsField;
        
        private string maxCritField;
        
        private string totalHealField;
        
        private string totalDmgField;
        
        private string totalTankField;
        
        private string totalHeroDmgField;
        
        private string totalHeroPhyDmgField;
        
        private string totalHeroMagicDmgField;
        
        private string totalHeroTrueDmgField;
        
        private items[] items_listField;
        
        /// <remarks/>
        public string matchId {
            get {
                return this.matchIdField;
            }
            set {
                this.matchIdField = value;
            }
        }
        
        /// <remarks/>
        public string playerId {
            get {
                return this.playerIdField;
            }
            set {
                this.playerIdField = value;
            }
        }
        
        /// <remarks/>
        public string gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
            }
        }
        
        /// <remarks/>
        public string KDA {
            get {
                return this.kDAField;
            }
            set {
                this.kDAField = value;
            }
        }
        
        /// <remarks/>
        public string champion_name {
            get {
                return this.champion_nameField;
            }
            set {
                this.champion_nameField = value;
            }
        }
        
        /// <remarks/>
        public string champion_name_ch {
            get {
                return this.champion_name_chField;
            }
            set {
                this.champion_name_chField = value;
            }
        }
        
        /// <remarks/>
        public string champIcon {
            get {
                return this.champIconField;
            }
            set {
                this.champIconField = value;
            }
        }
        
        /// <remarks/>
        public string firstSpellIcon {
            get {
                return this.firstSpellIconField;
            }
            set {
                this.firstSpellIconField = value;
            }
        }
        
        /// <remarks/>
        public string secondSpellIcon {
            get {
                return this.secondSpellIconField;
            }
            set {
                this.secondSpellIconField = value;
            }
        }
        
        /// <remarks/>
        public string warScore {
            get {
                return this.warScoreField;
            }
            set {
                this.warScoreField = value;
            }
        }
        
        /// <remarks/>
        public string lastHits {
            get {
                return this.lastHitsField;
            }
            set {
                this.lastHitsField = value;
            }
        }
        
        /// <remarks/>
        public string creeps {
            get {
                return this.creepsField;
            }
            set {
                this.creepsField = value;
            }
        }
        
        /// <remarks/>
        public string towersDestroyed {
            get {
                return this.towersDestroyedField;
            }
            set {
                this.towersDestroyedField = value;
            }
        }
        
        /// <remarks/>
        public string barracksDestroyed {
            get {
                return this.barracksDestroyedField;
            }
            set {
                this.barracksDestroyedField = value;
            }
        }
        
        /// <remarks/>
        public string wards {
            get {
                return this.wardsField;
            }
            set {
                this.wardsField = value;
            }
        }
        
        /// <remarks/>
        public string dewards {
            get {
                return this.dewardsField;
            }
            set {
                this.dewardsField = value;
            }
        }
        
        /// <remarks/>
        public string maxContKills {
            get {
                return this.maxContKillsField;
            }
            set {
                this.maxContKillsField = value;
            }
        }
        
        /// <remarks/>
        public string maxMultiKills {
            get {
                return this.maxMultiKillsField;
            }
            set {
                this.maxMultiKillsField = value;
            }
        }
        
        /// <remarks/>
        public string maxCrit {
            get {
                return this.maxCritField;
            }
            set {
                this.maxCritField = value;
            }
        }
        
        /// <remarks/>
        public string totalHeal {
            get {
                return this.totalHealField;
            }
            set {
                this.totalHealField = value;
            }
        }
        
        /// <remarks/>
        public string totalDmg {
            get {
                return this.totalDmgField;
            }
            set {
                this.totalDmgField = value;
            }
        }
        
        /// <remarks/>
        public string totalTank {
            get {
                return this.totalTankField;
            }
            set {
                this.totalTankField = value;
            }
        }
        
        /// <remarks/>
        public string totalHeroDmg {
            get {
                return this.totalHeroDmgField;
            }
            set {
                this.totalHeroDmgField = value;
            }
        }
        
        /// <remarks/>
        public string totalHeroPhyDmg {
            get {
                return this.totalHeroPhyDmgField;
            }
            set {
                this.totalHeroPhyDmgField = value;
            }
        }
        
        /// <remarks/>
        public string totalHeroMagicDmg {
            get {
                return this.totalHeroMagicDmgField;
            }
            set {
                this.totalHeroMagicDmgField = value;
            }
        }
        
        /// <remarks/>
        public string totalHeroTrueDmg {
            get {
                return this.totalHeroTrueDmgField;
            }
            set {
                this.totalHeroTrueDmgField = value;
            }
        }
        
        /// <remarks/>
        public items[] items_list {
            get {
                return this.items_listField;
            }
            set {
                this.items_listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class match {
        
        private string matchIdField;
        
        private string modeField;
        
        private string durationField;
        
        private string endTimeField;
        
        private string killsField;
        
        private string goldField;
        
        private matchDetails[] match_details_winField;
        
        private matchDetails[] match_details_lostField;
        
        /// <remarks/>
        public string matchId {
            get {
                return this.matchIdField;
            }
            set {
                this.matchIdField = value;
            }
        }
        
        /// <remarks/>
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public string kills {
            get {
                return this.killsField;
            }
            set {
                this.killsField = value;
            }
        }
        
        /// <remarks/>
        public string gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
            }
        }
        
        /// <remarks/>
        public matchDetails[] match_details_win {
            get {
                return this.match_details_winField;
            }
            set {
                this.match_details_winField = value;
            }
        }
        
        /// <remarks/>
        public matchDetails[] match_details_lost {
            get {
                return this.match_details_lostField;
            }
            set {
                this.match_details_lostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class match_list {
        
        private string idField;
        
        private string playerIdField;
        
        private string champion_name_chField;
        
        private string iconField;
        
        private string statusField;
        
        private string modeField;
        
        private string dateField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string playerId {
            get {
                return this.playerIdField;
            }
            set {
                this.playerIdField = value;
            }
        }
        
        /// <remarks/>
        public string champion_name_ch {
            get {
                return this.champion_name_chField;
            }
            set {
                this.champion_name_chField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class played_champs_display {
        
        private string iconField;
        
        private string championNameField;
        
        private string championNameCNField;
        
        private string winRateField;
        
        private string matchStatField;
        
        private string averageKDAField;
        
        private string averageKDARatingField;
        
        private string averageDamageField;
        
        private string averageEarnField;
        
        private string averageMinionsKilledField;
        
        private string totalMVPField;
        
        private string totalHopeField;
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string championName {
            get {
                return this.championNameField;
            }
            set {
                this.championNameField = value;
            }
        }
        
        /// <remarks/>
        public string championNameCN {
            get {
                return this.championNameCNField;
            }
            set {
                this.championNameCNField = value;
            }
        }
        
        /// <remarks/>
        public string winRate {
            get {
                return this.winRateField;
            }
            set {
                this.winRateField = value;
            }
        }
        
        /// <remarks/>
        public string matchStat {
            get {
                return this.matchStatField;
            }
            set {
                this.matchStatField = value;
            }
        }
        
        /// <remarks/>
        public string averageKDA {
            get {
                return this.averageKDAField;
            }
            set {
                this.averageKDAField = value;
            }
        }
        
        /// <remarks/>
        public string averageKDARating {
            get {
                return this.averageKDARatingField;
            }
            set {
                this.averageKDARatingField = value;
            }
        }
        
        /// <remarks/>
        public string averageDamage {
            get {
                return this.averageDamageField;
            }
            set {
                this.averageDamageField = value;
            }
        }
        
        /// <remarks/>
        public string averageEarn {
            get {
                return this.averageEarnField;
            }
            set {
                this.averageEarnField = value;
            }
        }
        
        /// <remarks/>
        public string averageMinionsKilled {
            get {
                return this.averageMinionsKilledField;
            }
            set {
                this.averageMinionsKilledField = value;
            }
        }
        
        /// <remarks/>
        public string totalMVP {
            get {
                return this.totalMVPField;
            }
            set {
                this.totalMVPField = value;
            }
        }
        
        /// <remarks/>
        public string totalHope {
            get {
                return this.totalHopeField;
            }
            set {
                this.totalHopeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class rank_statistics {
        
        private string typeField;
        
        private string rankField;
        
        private string pointField;
        
        private string total_matchesField;
        
        private string win_rateField;
        
        private string matches_winnedField;
        
        private string matches_lostField;
        
        private string update_datetimeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        public string point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public string total_matches {
            get {
                return this.total_matchesField;
            }
            set {
                this.total_matchesField = value;
            }
        }
        
        /// <remarks/>
        public string win_rate {
            get {
                return this.win_rateField;
            }
            set {
                this.win_rateField = value;
            }
        }
        
        /// <remarks/>
        public string matches_winned {
            get {
                return this.matches_winnedField;
            }
            set {
                this.matches_winnedField = value;
            }
        }
        
        /// <remarks/>
        public string matches_lost {
            get {
                return this.matches_lostField;
            }
            set {
                this.matches_lostField = value;
            }
        }
        
        /// <remarks/>
        public string update_datetime {
            get {
                return this.update_datetimeField;
            }
            set {
                this.update_datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class normal_statistics {
        
        private string typeField;
        
        private string total_matchesField;
        
        private string win_rateField;
        
        private string matches_winnedField;
        
        private string matches_lostField;
        
        private string update_datetimeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string total_matches {
            get {
                return this.total_matchesField;
            }
            set {
                this.total_matchesField = value;
            }
        }
        
        /// <remarks/>
        public string win_rate {
            get {
                return this.win_rateField;
            }
            set {
                this.win_rateField = value;
            }
        }
        
        /// <remarks/>
        public string matches_winned {
            get {
                return this.matches_winnedField;
            }
            set {
                this.matches_winnedField = value;
            }
        }
        
        /// <remarks/>
        public string matches_lost {
            get {
                return this.matches_lostField;
            }
            set {
                this.matches_lostField = value;
            }
        }
        
        /// <remarks/>
        public string update_datetime {
            get {
                return this.update_datetimeField;
            }
            set {
                this.update_datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetPlayerProfileCompletedEventHandler(object sender, GetPlayerProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlayerProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlayerProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public player_profile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((player_profile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void getMatchCompletedEventHandler(object sender, getMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public match Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((match)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591